# Generated by Django 5.2.5 on 2026-03-09 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_note'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RESOURCE_OPEN', 'Resource Open'), ('RESOURCE_CLOSE', 'Resource Close'), ('PAGE_VIEW', 'Page View'), ('PAGE_LEAVE', 'Page Leave'), ('SCROLL', 'Scroll'), ('TAB_HIDDEN', 'Tab Hidden'), ('TAB_VISIBLE', 'Tab Visible'), ('NOTE_CREATED', 'Note Created'), ('HIGHLIGHT', 'Highlight')], max_length=30)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('scroll_depth', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.pdfresource')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.studysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='tracking_le_user_id_167d26_idx'), models.Index(fields=['event_type'], name='tracking_le_event_t_c0eaf1_idx'), models.Index(fields=['created_at'], name='tracking_le_created_dc4f90_idx')],
            },
        ),
    ]
