# Generated by Django 5.2.5 on 2026-02-26 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfresource',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfresource',
            name='notes',
            field=models.TextField(blank=True, help_text='User notes / intent'),
        ),
        migrations.AddField(
            model_name='pdfresource',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='User-defined tags'),
        ),
        migrations.AddField(
            model_name='pdfresource',
            name='title_override',
            field=models.CharField(blank=True, help_text='User-defined title', max_length=255),
        ),
        migrations.AddField(
            model_name='pdfresource',
            name='total_view_time',
            field=models.PositiveIntegerField(default=0, help_text='Total time viewed in seconds'),
        ),
        migrations.AddField(
            model_name='pdfresource',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ResourceInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view_opened', 'View Opened'), ('view_closed', 'View Closed'), ('metadata_updated', 'Metadata Updated')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Seconds (for view_closed)', null=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='resources.pdfresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
